---
kind: pipeline
name: build
clone:
  depth: 1
volumes:
  - name: gopath
    temp: {}
steps:
  - name: download go modules
    image: golang:1.26.4@sha256:68cb6d68bed024785b69195b89af7ac7a444f27791435f98647edff595aa0479
    commands:
      - go mod download
    volumes: &volumes
      - name: gopath
        path: /go
  - name: test
    image: golang:1.26.4@sha256:68cb6d68bed024785b69195b89af7ac7a444f27791435f98647edff595aa0479
    commands:
      - go test -race -covermode=atomic ./...
    volumes: *volumes
