---
kind: pipeline
name: build
clone:
  depth: 1
volumes:
  - name: gopath
    temp: {}
steps:
  - name: download go modules
    image: golang:1.22.5@sha256:fcae9e0e7313c6467a7c6632ebb5e5fab99bd39bd5eb6ee34a211353e647827a
    commands:
      - go mod download
    volumes: &volumes
      - name: gopath
        path: /go
  - name: test
    image: golang:1.22.5@sha256:fcae9e0e7313c6467a7c6632ebb5e5fab99bd39bd5eb6ee34a211353e647827a
    commands:
      - go test -race -covermode=atomic ./...
    volumes: *volumes
