---
kind: pipeline
name: build
clone:
  depth: 1
volumes:
  - name: gopath
    temp: {}
steps:
  - name: download go modules
    image: golang:1.26.5@sha256:079e59808d2d252516e27e3f3a9c003740dee7f75e55aa71528766d52bcfc16a
    commands:
      - go mod download
    volumes: &volumes
      - name: gopath
        path: /go
  - name: test
    image: golang:1.26.5@sha256:079e59808d2d252516e27e3f3a9c003740dee7f75e55aa71528766d52bcfc16a
    commands:
      - go test -race -covermode=atomic ./...
    volumes: *volumes
