---
kind: pipeline
name: build
clone:
  depth: 1
volumes:
  - name: gopath
    temp: {}
steps:
  - name: download go modules
    image: golang:1.27.0@sha256:65b6f280bf050ec5af12716857e8ea8439d694dbba8f31ceeb7630670071f2bb
    commands:
      - go mod download
    volumes: &volumes
      - name: gopath
        path: /go
  - name: test
    image: golang:1.27.0@sha256:65b6f280bf050ec5af12716857e8ea8439d694dbba8f31ceeb7630670071f2bb
    commands:
      - go test -race -covermode=atomic ./...
    volumes: *volumes
