---
linters:
  enable-all: true
  disable:
    - tagliatelle
    - wsl
    - err113
    - nlreturn
    - lll
    - godot
    - godox
    - exhaustruct
    - varnamelen
    - depguard
    - exportloopref # WARN The linter 'exportloopref' is deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar. 
    - copyloopvar # WARN [linters_context] copyloopvar: this linter is disabled because the Go version (1.19) of your project is lower than Go 1.22 
    - intrange # WARN [linters_context] intrange: this linter is disabled because the Go version (1.19) of your project is lower than Go 1.22 
