version: "2"
linters:
  default: all
  disable:
    - copyloopvar
    - depguard
    - err113
    - exhaustruct
    - godot
    - godox
    - intrange
    - lll
    - nlreturn
    - tagliatelle
    - varnamelen
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
