version: 2.1
workflows:
  build:
    jobs:
      - test
jobs:
  test:
    docker:
      - image: golang:1.26.2@sha256:2a2b4b5791cea8ae09caecba7bad0bd9631def96e5fe362e4a5e67009fe4ae61
    steps:
      - checkout
      - run:
          name: go mod download
          command: go mod download
      - run:
          name: test
          command: go test -race -covermode=atomic ./...
