version: 2.1
workflows:
  build:
    jobs:
      - test
jobs:
  test:
    docker:
      - image: golang:1.27.1@sha256:512690a5660563b57d37ecc31129e7f136e831db2aed24a1dbeb8ad7380dc0fa
    steps:
      - checkout
      - run:
          name: go mod download
          command: go mod download
      - run:
          name: test
          command: go test -race -covermode=atomic ./...
