---
name: test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19.1'
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.47.2
    - name: test
      run: go test -v ./... -race -covermode=atomic
